# from https://github.com/marketplace/actions/build-and-push-docker-images#git-context
name: Docker build and push

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        default: '${{ github.event.repository.name }}'
        required: false
        type: string
      IMAGE_REGISTRY:
        default: 'quay.io'
        required: false
        type: string
      IMAGE_REGISTRY_NAMESPACE:
        default: 'fmi'
        required: false
        type: string
    secrets:
      IMAGE_REGISTRY_USER:
        required: true
      IMAGE_REGISTRY_TOKEN:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      GIT_SHORT_SHA: ${GITHUB_SHA:7}
      GIT_SHORT_SHA1: ${GITHUB_SHA:7}
      GIT_SHORT_SHA2: ${GITHUB_SHA::7}
      GIT_SHORT_SHA4: ${env.GITHUB_SHA::7}
      GIT_SHORT_SHA5: ${GITHUB_SHA}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dump
        run: |
          env
          echo "CUSTOM:"
          echo "1 ${{ env.GIT_SHORT_SHA1 }}"
          echo "2 ${{ env.GIT_SHORT_SHA2 }}"
          echo "3 ${{ env.GIT_SHORT_SHA3 }}"
          echo "4 ${{ env.GIT_SHORT_SHA4 }}"
          echo "5 ${{ env.GIT_SHORT_SHA5 }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Registry login
        uses: docker/login-action@v2
        with:
          registry: '${{ inputs.IMAGE_REGISTRY }}'
          username: '${{ secrets.IMAGE_REGISTRY_USER }}'
          password: '${{ secrets.IMAGE_REGISTRY_TOKEN }}'

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: '${{ inputs.IMAGE_REGISTRY_NAMESPACE }}/${{ inputs.IMAGE_NAME }}:${{ env.GIT_SHORT_SHA }}'
