# from https://github.com/marketplace/actions/build-and-push-docker-images#git-context
name: Docker build and push

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        default: '${{ github.event.repository.name }}'
        required: false
        type: string
      IMAGE_TAG:
        default: ''
        required: false
        type: string
      IMAGE_BUILD_CONTEXT:
        default: '.'
        required: false
        type: string
      IMAGE_REGISTRY:
        default: 'quay.io'
        required: false
        type: string
      IMAGE_REGISTRY_NAMESPACE:
        default: 'fmi'
        required: false
        type: string
      # TODO: implement this
      CREATE_LATEST_TAG:
        default: false
        required: false
        type: boolean
    secrets:
      IMAGE_REGISTRY_USER:
        required: true
      IMAGE_REGISTRY_TOKEN:
        required: true

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build-and-push:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Registry login
        uses: docker/login-action@v3
        with:
          registry: '${{ inputs.IMAGE_REGISTRY }}'
          username: '${{ secrets.IMAGE_REGISTRY_USER }}'
          password: '${{ secrets.IMAGE_REGISTRY_TOKEN }}'

      - name: Get short SHA tag
        if: ${{ inputs.IMAGE_TAG == '' }}
        uses: rlespinasse/github-slug-action@v4
        with:
          short-length: 7

      # TODO: Form tag (or list of tags) from inputs.IMAGE_TAG and inputs.CREATE_LATEST_TAG and combine 'Build and push with SHA tag'

      - name: Build and push with SHA tag
        if: ${{ inputs.IMAGE_TAG == '' }}
        uses: docker/build-push-action@v5
        with:
          context: '${{ IMAGE_BUILD_CONTEXT }}'
          push: true
          tags: '${{ inputs.IMAGE_REGISTRY }}/${{ inputs.IMAGE_REGISTRY_NAMESPACE }}/${{ inputs.IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }}'

      - name: Build and push with tag
        if: ${{ inputs.IMAGE_TAG != '' }}
        uses: docker/build-push-action@v5
        with:
          context: '${{ IMAGE_BUILD_CONTEXT }}'
          push: true
          tags: '${{ inputs.IMAGE_REGISTRY }}/${{ inputs.IMAGE_REGISTRY_NAMESPACE }}/${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}'
