# from https://github.com/marketplace/actions/build-and-push-docker-images#git-context
name: Docker build and push

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        default: '${{ github.event.repository.name }}'
        required: false
        type: string
      IMAGE_TAG:
        default: ''
        required: false
        type: string
      IMAGE_REGISTRY:
        default: 'quay.io'
        required: false
        type: string
      IMAGE_REGISTRY_NAMESPACE:
        default: 'fmi'
        required: false
        type: string
    secrets:
      IMAGE_REGISTRY_USER:
        required: true
      IMAGE_REGISTRY_TOKEN:
        required: true

#permissions:
#  actions: none
#  checks: none
#  contents: read
#  deployments: none
#  id-token: none
#  issues: none
#  discussions: none
#  packages: none
#  pages: none
#  pull-requests: none
#  repository-projects: none
#  security-events: none
#  statuses: none

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get short SHA tag
        if: ${{ inputs.IMAGE_TAG == '' }}
        uses: rlespinasse/github-slug-action@v4
        with:
          short-length: 7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Registry login
        uses: docker/login-action@v2
        with:
          registry: '${{ inputs.IMAGE_REGISTRY }}'
          username: '${{ secrets.IMAGE_REGISTRY_USER }}'
          password: '${{ secrets.IMAGE_REGISTRY_TOKEN }}'

      - name: Build and push with digest
        if: ${{ inputs.IMAGE_TAG == '' }}
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: '${{ inputs.IMAGE_REGISTRY }}/${{ inputs.IMAGE_REGISTRY_NAMESPACE }}/${{ inputs.IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }}'

      - name: Build and push with tag
        if: ${{ inputs.IMAGE_TAG != '' }}
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: '${{ inputs.IMAGE_REGISTRY }}/${{ inputs.IMAGE_REGISTRY_NAMESPACE }}/${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}'
